name: Deploy Test

on:
  push:
    branches:
      - release
    paths:
      - '**/**.js'
      - '**/**.ts'
      - '**/**.tc'
      - '**/**.gs'
env:
  REFRESH_TOKEN:
  CLIENT_ID:
  CLIENT_SECRET:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: install clasp
        run: sudo npm i @google/clasp -g

      - name: create clasprc
        uses: namaggarwal/clasp-token-action@v0.0.1
        with:
          client-id: ${{ secrets.GAS_CLIENT_ID }}
          client-secret: ${{ secrets.GAS_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GAS_REFRESH_TOKEN }}

      - name: push
        run: |
          cd src
          sudo clasp push --force

      - name: deploy
        run: |
          cd src
          sudo clasp deploy
